[project]
name = "open-cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe==0.10.14",
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
    "pynput==1.7.6",
]
